version: "2"
services:
  backend-drone-delivery:
    container_name: backend-drone-delivery
    #command: bash -c "npm run build && npm run start"
    build: 
     context: .
     dockerfile: Dockerfile
    volumes:
      - ./:/usr/src
    ports:
      - 3001:3000
